/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'freerots_blinky' 
 * Target:  'iflash_nxp_lpcxpresso_1114' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "LPC11xx.h"



#endif /* RTE_COMPONENTS_H */
